version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: moneycare_db
    restart: always
    environment:
      POSTGRES_USER: moneycare_user
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: moneycare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: moneycare_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: